### ISSUE TITLE
Create extract_number()

### ISSUE THREAD

**Issue by jjcurtin** [jjcurtin/lab_support#2]
@KendraPaquette , this one will be harder.  It should strip the country code and return a single character string of the number without the code and without any other non-digits.  We will need to figure out how to handle/flag numbers that might be problematic (i.e., dont make sense).   We need to also consider what to do with SMS numbers that can be 5-6 (short codes) or other US numbers that are short.   Lets talk more about this before either of us attempt this.  Eventually, this function will replace the number functions we are currently using

**Comment by jjcurtin** [comment]
Test data from Kendra

test <- c("608 555-3636", "+17143227807", "+12226666444", "222 343-6666", "alphabet", "6086185323")
test
map(test, extract_number) %>%  unlist()

**Comment by jjcurtin** [comment]
test <- c("608 555-3636", "+17143227807", "+12226666444", "222 343-6666", "alphabet", "6086185323", "*67 6082176221", "16088431250", "(608) 212-5555")
test
map(test, extract_number) %>% unlist()

**Comment by KendraPaquette** [comment]
`library(tidyverse)`

`numbers <- c("(608) 228-1729", "+18473665275", "helloworld@gmail.com", "#CMAS#AMBER", "helloworld@gmail", "16082526200", "55555", "8665797172", "*676084383784", "*69", "+9122932715", "+911127233190")`

`map(numbers, extract_number) %>%  unlist()`

**Comment by KendraPaquette** [comment]
@jjcurtin The extract_number function is updated and working except for the email regex. It did not correctly flag the email without a '.' as incorrect. I am still working on this but wanted to update you since the rest of the function is working well!
 (see code above).
