### ISSUE TITLE
Update patterns in extract_number() for currently undefined numbers

### ISSUE THREAD

**Issue by jjcurtin** [jjcurtin/lab_support#24]
These are noted as not matched when reducing RISK2
+1 414-249-0226
+1 804-305-8010,

And this warning suggests that maybe we are not catching ""  or NA or NULL properly
Warning in .f(.x[[i]], ...): did not match any pre-defined pattern

**Comment by jjcurtin** [comment]
Note that +1 414-249-0226, includes a comma at the end.  That is why it does not match.   Test if a phone will dial when we type a comma.  If this is a wrong number that wont dial, leave it as such and just return the text number.   If it dials, we should correct it.

**Comment by KendraPaquette** [comment]
John - does the 414 or 804 number have a comma (or both)?

Also, I looked into the comma. It is impossible to dial a comma on iPhone - you can't dial a comma or save a comma in a stored contact. Even if you copy and paste it the comma gets removed. On my android test phone, it looks like you can dial a comma if you copy and paste it but I don't have cell service to see if the call will go through.

**Comment by jjcurtin** [comment]
@KendraPaquette , the 414 does have a comma at the end in the RISK2 data.   I don't remember the issue for the 804 but you should be able to see warnings for both if you run this code with the RISK2 project loaded

```{r, subid}
site <- "live"  # test or live
the_subid <- 1006
```

Absolute paths
```{r}
path_admin <- "P:/administration"
path_lab_support <- "P:/toolboxes/lab_support"
path_out <- "P:/studydata/risk2/knits/tmp"
```

Packages for lab workflow
```{r, packages_workflow, message=FALSE, warning=FALSE}
library(conflicted) # detect and warn about function conflicts
library(here)
```

Packages for script
```{r, packages_scripts, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```

Sources for script
```{r, source, message=FALSE, warning=FALSE}
source(here("functions", "fun_star.R"))
```


### Get Raw Data

Log in and get relevant STAR raw data for subid
```{r, login}
login_creds <- login_star(site)

voice <- get_star_data("voice", login_creds) %>% 
  dplyr::filter(subid == the_subid)
sms <- get_star_data("sms", login_creds) %>% 
  dplyr::filter(subid == the_subid)

end_date <- Sys.Date()
start_date <- end_date - days(30)

people_past <- get_context(the_subid, login_creds)$people
```


# Log in and get relevant STAR raw data for subid
login_creds <- login_star(site)

voice <- get_star_data("voice", login_creds) %>% 
  dplyr::filter(subid == the_subid)

sms <- get_star_data("sms", login_creds) %>% 
  dplyr::filter(subid == the_subid)

**Comment by jjcurtin** [comment]
@KendraPaquette , I think you created the issue_24 branch, is that true?  If so, a couple of things.  First, can you confirm that you have pushed all of your commits to github so that I can get my copy of this branch up to date with yours?  Second, lets start labeling branches with issue_##_shortdescription.    The _shortdescription will make it easier to tell what each branch is about without having to look up the issue## on github.  Thanks!

**Comment by KendraPaquette** [comment]
@jjcurtin - yes I created issue_24 branch. Github is up to date (only 2 small commits). Also, I think that new naming convention sounds good!
